name: Build and Sign EXE

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-sign:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --icon=compare.ico --noconsole --name="ComparisonTool" ComparisonToolGUI.py

      - name: Upload Unsigned EXE
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-exe
          path: dist/ComparisonTool.exe

      - name: Submit EXE for Signing
        env:
          SIGNPATH_API_KEY: ${{ secrets.SIGNPATH_API_KEY }}
          SIGNPATH_PROJECT_ID: ${{ secrets.SIGNPATH_PROJECT_ID }}
          SIGNPATH_ORGANIZATION_ID: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
        run: |
          curl -X POST "https://app.signpath.io/api/v1/${{ secrets.SIGNPATH_ORGANIZATION_ID }}/projects/${{ secrets.SIGNPATH_PROJECT_ID }}/sign" `
            -H "Authorization: Bearer $env:SIGNPATH_API_KEY" `
            -F "file=@dist/ComparisonTool.exe" `
            -o signed-ComparisonTool.exe

      - name: Check SignPath.io signing status
        run: curl -H "Authorization:Bearer ${{ secrets.SIGNPATH_API_KEY }}" \
          "https://app.signpath.io/api/v1/organizations/841f68d8-a83e-4cd1-97b9-81dd4543b577/projects/889f7288-128d-41bb-8a5d-e1948cbcb1b0/signing-jobs"

      - name: Upload Signed EXE
        uses: actions/upload-artifact@v4
        with:
          name: signed-exe
          path: signed-ComparisonTool.exe
